### ISSUE TITLE
Can't register plugins with flake8 / stevedore

### ISSUE THREAD

**Issue by epage** [sdispater/poet#1]
flake8 / [stevedore](https://docs.openstack.org/developer/stevedore/) use the general entry_points feature to register plugins

For example
```
    entry_points={
        flake8_entry_point: [
            'X = flake8_example:ExamplePlugin',
        ],
    },
```
See http://flake8.pycqa.org/en/latest/plugin-development/registering-plugins.html

**Comment by sdispater** [comment]
Maybe something like this could be a good notation:

```toml
[entry-points] # Optional super table

[entry-points."flake8.extension"]
X = "flake8_example:ExamplePlugin"
X101 = "flake8_example.ExamplePlugin"
```

What do you think?
