### ISSUE TITLE
Support dependencies for specific Python versions

### ISSUE THREAD

**Issue by sdispater** [sdispater/poet#4]
Poet should support dependencies for specific Python versions:

```toml
[dependencies]
requests = { version = "^2.13", python = "~2.7" }
```
