### ISSUE TITLE
RFE: ability to install dependency via remote ZIP file

### ISSUE THREAD

**Issue by PAStheLoD** [sdispater/poet#8]
Hello,

Is it possible to specify a zipball of a python setuptools project? (Basically the equivalent of the requirements.txt feature of supporting https://github.com/blabla.zip#egg=SomePyPkg )

Thanks and thanks for trying to make a sane package/dependency manger for python!

**Comment by sdispater** [comment]
Installing from an archive is not currently supported.

However, if you want to install from github you can declare you dependency like so:

```toml
blabla = { git = "https://github.com/blabla/blabla.git", branch = "master" }
blabla = { git = "https://github.com/blabla/blabla.git", tag = "0.1.2" }
blabla = { git = "https://github.com/blabla/blabla.git", rev = "d12189e2076fbdb40ed4902b2b4d9579003c607c" }
```
