### ISSUE TITLE
Document/finish entry_points support

### ISSUE THREAD

**Issue by maxrothman** [sdispater/poet#9]
[It looks like arbitrary `entry_points` might already be supported](https://github.com/sdispater/poet/blob/76e43edbecc37ffc2253ba433dac70aeb247c2e9/poet/poet.py#L228), but that's not reflected in the docs. Is it already done and just needs to be documented, or is there some additional work necessary to get it across the line? Either way, I'd be happy to make a PR if you can point me in the right direction.

Thanks for building this project, I'm really looking forward to watching it mature!

**Comment by sdispater** [comment]
Yes, it's not documented yet but is indeed supported:

```toml
[entry-points] # Optional super table

[entry-points."flake8.extension"]
X = "flake8_example:ExamplePlugin"
X101 = "flake8_example.ExamplePlugin"
```
